### ISSUE TITLE
Error when reloading with Gnome Shell Extension Reloader

### ISSUE THREAD

**Issue by tobias47n9e** [EasyScreenCast/EasyScreenCast#123]
When reloading the extension with Gnome Shell Extension Reloader this error appears:

## Expected Behavior
The extension should reload correctly.

## Current Behavior
The extension can't be reloaded.

## Possible Solution
The maintainer of Gnome Shell Extension Reloader explained to me that the bug is due to the import of `prefs.js` which is something that breaks the extension.

- All imports of `prefs.js` need to be removed
- The settings stored in `prefs.js` need to be stored in a different js file

## Steps to Reproduce (for bugs)
The current version 0.9.9 and the Gnome Shell Extension Reloader (https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/) need to be installed. Reloading the EasyScreenCast extension triggers the error.

## Logs
```
Gjs-Message: JS LOG: Reloading : EasyScreenCast@iacopodeenosee.gmail.com
(gnome-shell:1555): Gjs-WARNING **: JS ERROR: Exception in method call: ReloadExtension: Error: Type name EasyScreenCastSettingsWidget is already registered
GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:145
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
@/home/tobias/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:633
@/home/tobias/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/convenience.js:35
@/home/tobias/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/extension.js:34
initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:167
reloadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:202
GnomeShellExtensions<.ReloadExtension@resource:///org/gnome/shell/ui/shellDBus.js:411
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
_handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:261
_wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:331
Traceback (most recent call last):
  File "/home/tobias/.local/share/gnome-shell/extensions/extension-reloader@nls1729/gnome-shell-extension-tool", line 232, in <module>
    main()
  File "/home/tobias/.local/share/gnome-shell/extensions/extension-reloader@nls1729/gnome-shell-extension-tool", line 225, in main
    reload_extension(options.reload)
  File "/home/tobias/.local/share/gnome-shell/extensions/extension-reloader@nls1729/gnome-shell-extension-tool", line 194, in reload_extension
    None)
GLib.Error: g-io-error-quark: GDBus.Error:org.gnome.gjs.JSError.Error: Type name EasyScreenCastSettingsWidget is already registered (36)
```

## Your Environment
Fedora 24 / Fedora 25

**Comment by tobias47n9e** [comment]
This was solved by: https://github.com/EasyScreenCast/EasyScreenCast/pull/131
